// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: order_payment.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_order_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_order_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_order_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_order_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinAmount     int64                  `protobuf:"varint,1,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     int64                  `protobuf:"varint,2,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_order_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_order_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ListPaymentsRequest) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *ListPaymentsRequest) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*PaymentResponse     `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_order_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_order_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ListPaymentsResponse) GetPayments() []*PaymentResponse {
	if x != nil {
		return x.Payments
	}
	return nil
}

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_order_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_order_payment_proto_rawDescGZIP(), []int{4}
}

func (x *OrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OrderStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusUpdate) Reset() {
	*x = OrderStatusUpdate{}
	mi := &file_order_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusUpdate) ProtoMessage() {}

func (x *OrderStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_order_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusUpdate.ProtoReflect.Descriptor instead.
func (*OrderStatusUpdate) Descriptor() ([]byte, []int) {
	return file_order_payment_proto_rawDescGZIP(), []int{5}
}

func (x *OrderStatusUpdate) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatusUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderStatusUpdate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_order_payment_proto protoreflect.FileDescriptor

const file_order_payment_proto_rawDesc = "" +
	"\n" +
	"\x13order_payment.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x0ePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"h\n" +
	"\x0fPaymentResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"S\n" +
	"\x13ListPaymentsRequest\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x01 \x01(\x03R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x02 \x01(\x03R\tmaxAmount\"H\n" +
	"\x14ListPaymentsResponse\x120\n" +
	"\bpayments\x18\x01 \x03(\v2\x14.api.PaymentResponseR\bpayments\")\n" +
	"\fOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x81\x01\n" +
	"\x11OrderStatusUpdate\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\x92\x01\n" +
	"\x0ePaymentService\x12;\n" +
	"\x0eProcessPayment\x12\x13.api.PaymentRequest\x1a\x14.api.PaymentResponse\x12C\n" +
	"\fListPayments\x12\x18.api.ListPaymentsRequest\x1a\x19.api.ListPaymentsResponse2V\n" +
	"\fOrderService\x12F\n" +
	"\x17SubscribeToOrderUpdates\x12\x11.api.OrderRequest\x1a\x16.api.OrderStatusUpdate0\x01B/Z-github.com/erooohaaa/orders-generated/api;apib\x06proto3"

var (
	file_order_payment_proto_rawDescOnce sync.Once
	file_order_payment_proto_rawDescData []byte
)

func file_order_payment_proto_rawDescGZIP() []byte {
	file_order_payment_proto_rawDescOnce.Do(func() {
		file_order_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_payment_proto_rawDesc), len(file_order_payment_proto_rawDesc)))
	})
	return file_order_payment_proto_rawDescData
}

var file_order_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_order_payment_proto_goTypes = []any{
	(*PaymentRequest)(nil),        // 0: api.PaymentRequest
	(*PaymentResponse)(nil),       // 1: api.PaymentResponse
	(*ListPaymentsRequest)(nil),   // 2: api.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),  // 3: api.ListPaymentsResponse
	(*OrderRequest)(nil),          // 4: api.OrderRequest
	(*OrderStatusUpdate)(nil),     // 5: api.OrderStatusUpdate
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_order_payment_proto_depIdxs = []int32{
	1, // 0: api.ListPaymentsResponse.payments:type_name -> api.PaymentResponse
	6, // 1: api.OrderStatusUpdate.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: api.PaymentService.ProcessPayment:input_type -> api.PaymentRequest
	2, // 3: api.PaymentService.ListPayments:input_type -> api.ListPaymentsRequest
	4, // 4: api.OrderService.SubscribeToOrderUpdates:input_type -> api.OrderRequest
	1, // 5: api.PaymentService.ProcessPayment:output_type -> api.PaymentResponse
	3, // 6: api.PaymentService.ListPayments:output_type -> api.ListPaymentsResponse
	5, // 7: api.OrderService.SubscribeToOrderUpdates:output_type -> api.OrderStatusUpdate
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_payment_proto_init() }
func file_order_payment_proto_init() {
	if File_order_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_payment_proto_rawDesc), len(file_order_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_order_payment_proto_goTypes,
		DependencyIndexes: file_order_payment_proto_depIdxs,
		MessageInfos:      file_order_payment_proto_msgTypes,
	}.Build()
	File_order_payment_proto = out.File
	file_order_payment_proto_goTypes = nil
	file_order_payment_proto_depIdxs = nil
}
